import {Customers} from "@/app/dashboard/contacts/columns";

// export async function getData(): Promise<Customers[]> {
//     // Fetch data from your API here.
//     return [
//         {
//             id: 1,
//             name: "John Doe",
//             email: "john@example.com",
//             phone: "555-1234",
//             company: "Acme Inc.",
//             group: "Clients",
//         },
//         {
//             id: 2,
//             name: "Jane Smith",
//             email: "jane@example.com",
//             phone: "555-5678",
//             company: "Globex Corp.",
//             group: "Leads",
//         },
//         {
//             id: 3,
//             name: "Bob Johnson",
//             email: "bob@example.com",
//             phone: "555-9012",
//             company: "Stark Industries",
//             group: "Clients",
//         },
//         {
//             id: 4,
//             name: "Emily Davis",
//             email: "emily@example.com",
//             phone: "555-3456",
//             company: "Acme Inc.",
//             group: "Leads",
//         },
//         {
//             id: 5,
//             name: "Michael Brown",
//             email: "michael@example.com",
//             phone: "555-7890",
//             company: "Globex Corp.",
//             group: "Clients",
//         },
//         {
//             id: 1,
//             name: "John Doe",
//             email: "john@example.com",
//             phone: "555-1234",
//             company: "Acme Inc.",
//             group: "Clients",
//         },
//         {
//             id: 2,
//             name: "Jane Smith",
//             email: "jane@example.com",
//             phone: "555-5678",
//             company: "Globex Corp.",
//             group: "Leads",
//         },
//         {
//             id: 3,
//             name: "Bob Johnson",
//             email: "bob@example.com",
//             phone: "555-9012",
//             company: "Stark Industries",
//             group: "Clients",
//         },
//         {
//             id: 4,
//             name: "Emily Davis",
//             email: "emily@example.com",
//             phone: "555-3456",
//             company: "Acme Inc.",
//             group: "Leads",
//         },
//         {
//             id: 5,
//             name: "Michael Brown",
//             email: "michael@example.com",
//             phone: "555-7890",
//             company: "Globex Corp.",
//             group: "Clients",
//         },
//         {
//             id: 1,
//             name: "John Doe",
//             email: "john@example.com",
//             phone: "555-1234",
//             company: "Acme Inc.",
//             group: "Clients",
//         },
//         {
//             id: 2,
//             name: "Jane Smith",
//             email: "jane@example.com",
//             phone: "555-5678",
//             company: "Globex Corp.",
//             group: "Leads",
//         },
//         {
//             id: 3,
//             name: "Bob Johnson",
//             email: "bob@example.com",
//             phone: "555-9012",
//             company: "Stark Industries",
//             group: "Clients",
//         },
//         {
//             id: 4,
//             name: "Emily Davis",
//             email: "emily@example.com",
//             phone: "555-3456",
//             company: "Acme Inc.",
//             group: "Leads",
//         },
//         {
//             id: 5,
//             name: "Michael Brown",
//             email: "michael@example.com",
//             phone: "555-7890",
//             company: "Globex Corp.",
//             group: "Clients",
//         },
//         {
//             id: 1,
//             name: "John Doe",
//             email: "john@example.com",
//             phone: "555-1234",
//             company: "Acme Inc.",
//             group: "Clients",
//         },
//         {
//             id: 2,
//             name: "Jane Smith",
//             email: "jane@example.com",
//             phone: "555-5678",
//             company: "Globex Corp.",
//             group: "Leads",
//         },
//         {
//             id: 3,
//             name: "Bob Johnson",
//             email: "bob@example.com",
//             phone: "555-9012",
//             company: "Stark Industries",
//             group: "Clients",
//         },
//         {
//             id: 4,
//             name: "Emily Davis",
//             email: "emily@example.com",
//             phone: "555-3456",
//             company: "Acme Inc.",
//             group: "Leads",
//         },
//         {
//             id: 5,
//             name: "Michael Brown",
//             email: "michael@example.com",
//             phone: "555-7890",
//             company: "Globex Corp.",
//             group: "Clients",
//         },
//         {
//             id: 1,
//             name: "John Doe",
//             email: "john@example.com",
//             phone: "555-1234",
//             company: "Acme Inc.",
//             group: "Clients",
//         },
//         {
//             id: 2,
//             name: "Jane Smith",
//             email: "jane@example.com",
//             phone: "555-5678",
//             company: "Globex Corp.",
//             group: "Leads",
//         },
//         {
//             id: 3,
//             name: "Bob Johnson",
//             email: "bob@example.com",
//             phone: "555-9012",
//             company: "Stark Industries",
//             group: "Clients",
//         },
//         {
//             id: 4,
//             name: "Emily Davis",
//             email: "emily@example.com",
//             phone: "555-3456",
//             company: "Acme Inc.",
//             group: "Leads",
//         },
//         {
//             id: 5,
//             name: "Michael Brown",
//             email: "michael@example.com",
//             phone: "555-7890",
//             company: "Globex Corp.",
//             group: "Clients",
//         }
//     ]
// }
export function getData() {
    // Fetch data from your API here.
    return [
        {
            id: 1,
            name: "John Doe",
            email: "john@example.com",
            phone: "555-1234",
            company: "Acme Inc.",
            group: "Clients",
        },
        {
            id: 2,
            name: "Jane Smith",
            email: "jane@example.com",
            phone: "555-5678",
            company: "Globex Corp.",
            group: "Leads",
        },
        {
            id: 3,
            name: "Bob Johnson",
            email: "bob@example.com",
            phone: "555-9012",
            company: "Stark Industries",
            group: "Clients",
        },
        {
            id: 4,
            name: "Emily Davis",
            email: "emily@example.com",
            phone: "555-3456",
            company: "Acme Inc.",
            group: "Leads",
        },
        {
            id: 5,
            name: "Michael Brown",
            email: "michael@example.com",
            phone: "555-7890",
            company: "Globex Corp.",
            group: "Clients",
        },
        {
            id: 1,
            name: "John Doe",
            email: "john@example.com",
            phone: "555-1234",
            company: "Acme Inc.",
            group: "Clients",
        },
        {
            id: 2,
            name: "Jane Smith",
            email: "jane@example.com",
            phone: "555-5678",
            company: "Globex Corp.",
            group: "Leads",
        },
        {
            id: 3,
            name: "Bob Johnson",
            email: "bob@example.com",
            phone: "555-9012",
            company: "Stark Industries",
            group: "Clients",
        },
        {
            id: 4,
            name: "Emily Davis",
            email: "emily@example.com",
            phone: "555-3456",
            company: "Acme Inc.",
            group: "Leads",
        },
        {
            id: 5,
            name: "Michael Brown",
            email: "michael@example.com",
            phone: "555-7890",
            company: "Globex Corp.",
            group: "Clients",
        },
        {
            id: 1,
            name: "John Doe",
            email: "john@example.com",
            phone: "555-1234",
            company: "Acme Inc.",
            group: "Clients",
        },
        {
            id: 2,
            name: "Jane Smith",
            email: "jane@example.com",
            phone: "555-5678",
            company: "Globex Corp.",
            group: "Leads",
        },
        {
            id: 3,
            name: "Bob Johnson",
            email: "bob@example.com",
            phone: "555-9012",
            company: "Stark Industries",
            group: "Clients",
        },
        {
            id: 4,
            name: "Emily Davis",
            email: "emily@example.com",
            phone: "555-3456",
            company: "Acme Inc.",
            group: "Leads",
        },
        {
            id: 5,
            name: "Michael Brown",
            email: "michael@example.com",
            phone: "555-7890",
            company: "Globex Corp.",
            group: "Clients",
        },
        {
            id: 1,
            name: "John Doe",
            email: "john@example.com",
            phone: "555-1234",
            company: "Acme Inc.",
            group: "Clients",
        },
        {
            id: 2,
            name: "Jane Smith",
            email: "jane@example.com",
            phone: "555-5678",
            company: "Globex Corp.",
            group: "Leads",
        },
        {
            id: 3,
            name: "Bob Johnson",
            email: "bob@example.com",
            phone: "555-9012",
            company: "Stark Industries",
            group: "Clients",
        },
        {
            id: 4,
            name: "Emily Davis",
            email: "emily@example.com",
            phone: "555-3456",
            company: "Acme Inc.",
            group: "Leads",
        },
        {
            id: 5,
            name: "Michael Brown",
            email: "michael@example.com",
            phone: "555-7890",
            company: "Globex Corp.",
            group: "Clients",
        },
        {
            id: 1,
            name: "John Doe",
            email: "john@example.com",
            phone: "555-1234",
            company: "Acme Inc.",
            group: "Clients",
        },
        {
            id: 2,
            name: "Jane Smith",
            email: "jane@example.com",
            phone: "555-5678",
            company: "Globex Corp.",
            group: "Leads",
        },
        {
            id: 3,
            name: "Bob Johnson",
            email: "bob@example.com",
            phone: "555-9012",
            company: "Stark Industries",
            group: "Clients",
        },
        {
            id: 4,
            name: "Emily Davis",
            email: "emily@example.com",
            phone: "555-3456",
            company: "Acme Inc.",
            group: "Leads",
        },
        {
            id: 5,
            name: "Michael Brown",
            email: "michael@example.com",
            phone: "555-7890",
            company: "Globex Corp.",
            group: "Clients",
        }
    ]
}

export function getDataById(id: string) {

}